### PR TITLE
Missing refresh of tool setting source on mount

### LINKED ISSUE #378: ToolSettings string editor fails to sync properly
**Describe the bug**
Docking and undocking toolsettings widget causes standard string editor property to display outdated values.

**To Reproduce**
Have a tool that supplies and updates toolsettings string value with `syncToolSettingsProperties`
Update the value.
Undock toolsettings.

Tool to reproduce:
```typescript
export class TestToolSettings extends PrimitiveTool {
  public static override toolId = "TestToolSettings";
  public constructor(private _counter = 0) { super(); }
  public override async onRestartTool() { }
  public override async onDataButtonDown(): Promise<EventHandled> {
    this._counter++;
    this.syncToolSettingsProperties([{ value: { value: this._counter.toString() }, propertyName: "counter" }]);
    return EventHandled.Yes;
  }
  public override async applyToolSettingPropertyChange(updated: DialogPropertySyncItem): Promise<boolean> {
    if (updated.propertyName === "counter" && typeof updated.value.value === "string") {
      const num = Number.parseInt(updated.value.value, 10);
      this._counter = isNaN(num) ? 0 : num;
      this.syncToolSettingsProperties([{ ...updated, value: { value: this._counter } }]);
      return true;
    }
    return false;
  }
  public override supplyToolSettingsProperties(): DialogItem[] {
    return [{
      value: { value: this._counter.toString() },
      property: {
        name: "counter",
        displayLabel: "",
        typename: StandardTypeNames.String,
      },
      editorPosition: { rowPriority: 0, columnIndex: 0 },
    }];
  }
}
```

Or modify SampleTool.ts:

```typescript
public override async onKeyTransition(down: boolean, ev: KeyboardEvent) {
    if (down && ev.key === "q") {
      this._stateValue.value = ev.key.concat(this._stateValue.value as string ?? "");
      this.syncToolSettingsProperties([{ propertyName: SampleTool._stateName, value: this._stateValue }]);
    }
    return EventHandled.Yes;
  }
```
and toolsettings must be supplied with new object:
```typescript
toolSettings.push({
      // value: this._stateValue,
      value: { ...this._stateValue },  // new object causes problems
      property: SampleTool._getStateDescription(),
      editorPosition: { rowPriority: 10, columnIndex: 4 },
    });
```

**Expected behavior**
UI and internal state always in sync

**Screenshots**
testtool:
image
image

modified sampletool.ts:
image
image

**Desktop (please complete the applicable information):**

- Windows10
- Electron 17.4.11
- iTwin.js AppUI Version 3.7.6
- iTwin.js Version 3.7.6

**Additional context**
UI refreshes after tool gets unsuspended from any view tool.

### PR DESCRIPTION
**Pull request by raplemie**
## Changes

When mounting toolSettings in Docked or Widget form, will refresh the settings from the tool.
Added same forceRefresh fix on node changes to Widget form than always existed in Docked form

## Testing

Validated cover and e2e.
Added relevant e2e test to validate that tool settings gets correctly updating when changing docked/widget.

## Issue
Resolves #378

### CODE REVIEW

**Review by joehenry9498 — APPROVED** [review]
Functionality working as expected and code looks good as well. Just needs a master merge

**Comment by joehenry9498** [comment]
Needs a next version.md

**Comment by raplemie** [comment]
> Needs a next version.md

Thanks, I was convinced I had one !!!

**Comment by joehenry9498** [comment]
@Mergifyio backport release/4.6.x

**Pull request merged**
